# Generated by Django 4.1 on 2023-01-20 08:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ManyToManyField(to='app_admin.course')),
                ('period', models.ManyToManyField(to='app_admin.period')),
                ('school_class', models.ManyToManyField(to='app_admin.schoolclass')),
                ('staff', models.ManyToManyField(to='app_admin.staff')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Cotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.course')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.period')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.student')),
            ],
        ),
        migrations.CreateModel(
            name='Comportement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conduite', models.CharField(choices=[('impoli', 'Impoli'), ('poli', 'Poli')], max_length=30)),
                ('decision', models.CharField(choices=[('passe', 'Passe'), ('echouer', 'Echouer')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.period')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.student')),
            ],
        ),
    ]
