# Generated by Django 4.1 on 2023-01-02 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.course')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.period')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.staff')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Cotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.course')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.period')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.student')),
            ],
        ),
        migrations.CreateModel(
            name='Comportement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conduite', models.CharField(max_length=30)),
                ('decision', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.period')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.student')),
            ],
        ),
    ]
