# Generated by Django 4.1 on 2023-01-02 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comportement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_staff.comportement')),
                ('cote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_staff.cotation')),
            ],
        ),
    ]
