# Generated by Django 4.1 on 2023-01-19 14:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conduite', models.CharField(choices=[('impoli', 'Impoli'), ('poli', 'Poli')], max_length=30)),
                ('decision', models.CharField(choices=[('passe', 'Passe'), ('echouer', 'Echouer')], max_length=30)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.admin')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.student')),
            ],
        ),
    ]
