# Generated by Django 4.1 on 2023-01-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bulletin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletin',
            name='conduite',
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='decision',
        ),
    ]
