# Generated by Django 4.1 on 2023-01-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='period_num',
        ),
        migrations.AlterField(
            model_name='period',
            name='period_name',
            field=models.CharField(choices=[('1erep', '1ere p'), ('2emep', '2ème P'), ('3emep', '3ème P'), ("'4emep", '4ème P')], default='1erep', max_length=50),
        ),
    ]
