# Generated by Django 4.1 on 2023-01-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_user_firstname_user_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='class_name',
            field=models.CharField(max_length=25),
        ),
    ]
