# Generated by Django 4.1 on 2023-01-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_alter_schoolclass_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
    ]
