# Generated by Django 4.1 on 2023-01-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_alter_period_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='period_name',
            field=models.CharField(choices=[('1erep', '1ere p'), ('2emep', '2ème P'), ('examen1', 'Examen 1'), ('3emep', '3ème P'), ("'4emep", '4ème P'), ('examen2', 'Examen 2')], default='1erep', max_length=50),
        ),
    ]
