# Generated by Django 4.1 on 2023-01-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0004_alter_period_period_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='period',
            name='period_name',
            field=models.CharField(choices=[('1erep', '1ere p'), ('2emep', '2ème P'), ('examen1', 'Examen 1'), ('3emep', '3ème P'), ('4emep', '4ème P'), ('examen2', 'Examen 2')], default='1erep', max_length=50),
        ),
    ]
