# Generated by Django 4.1 on 2023-01-03 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0005_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_num',
            field=models.IntegerField(null=True),
        ),
    ]
