# Generated by Django 4.1 on 2023-01-04 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0007_alter_student_school_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.admin')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.staff')),
            ],
        ),
    ]
