# Generated by Django 4.1 on 2023-01-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0009_remove_staff_course_course_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='period_name',
            field=models.CharField(max_length=50),
        ),
    ]
