# Generated by Django 4.1 on 2023-01-03 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0007_alter_student_school_class'),
        ('app_public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleblog',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.admin'),
        ),
        migrations.AlterField(
            model_name='articleblog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_public.category'),
        ),
    ]
