# Generated by Django 4.1 on 2023-01-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_public', '0002_alter_articleblog_admin_alter_articleblog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleblog',
            name='slug',
        ),
    ]
